# Generated by Django 4.2.7 on 2023-12-01 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voltrium', '0007_order_order_date_alter_order_total_amount_orderline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
