# Generated by Django 4.2.7 on 2023-12-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voltrium', '0008_remove_payment_payment_amount_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='review_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
