# Generated by Django 4.2.7 on 2023-12-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voltrium', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
